#!/bin/bash
# GitHub 仓库创建和推送脚本

echo "=========================================="
echo "无人机代码推送到 GitHub"
echo "=========================================="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "步骤 1: 在浏览器中打开 https://github.com/new"
echo ""
echo "步骤 2: 填写以下信息："
echo "  - Repository name: uav-autonomous-exploration"
echo "  - Description: 基于 FUEL + FAST-LIO + PX4 的自主探索无人机系统"
echo "  - Public 或 Private: 根据需要选择"
echo "  - 不要勾选 'Initialize this repository with a README'"
echo ""
echo "步骤 3: 创建后，GitHub 会显示推送命令，或者直接运行："
echo ""
echo "  git remote add origin https://github.com/dytklmf-sketch/uav-autonomous-exploration.git"
echo "  git push -u origin main"
echo ""
echo "或使用 SSH（如果已配置）："
echo ""
echo "  git remote add origin git@github.com:dytklmf-sketch/uav-autonomous-exploration.git"
echo "  git push -u origin main"
echo ""
echo "=========================================="
echo "当前仓库状态："
echo "=========================================="
git log --oneline -1
echo ""
git status
echo ""
echo "=========================================="
echo "准备好后，请复制上面的命令执行"
echo "=========================================="
